export { default as Layout } from './layout'
export { default as Footer } from './footer'
export { default as Header } from './header'
export { default as Head } from './html-head'
export { default as SideModal } from './sidemodal'
